### ISSUE TITLE
Show interfaces

### ISSUE THREAD

**Issue by spetitjean** [xmg-hhu/xmg-webgui#11]
The <iface> dimension is not displayed yet by the viewer. It would just be an additional feature structure, but I am not sure where it should be shown (directly next to the tree or in its own screen section).

**Comment by spetitjean** [comment]
Experimental support on the development version ([sandbox](http://xmg.phil.hhu.de/TEST/simonsandbox)).

**Comment by timmli** [comment]
Is this view now available? Would be cool! If that is the case, maybe you could equip the starting example with a small interface? Also, a frame description could be added. Thanks!

**Comment by spetitjean** [comment]
It's still available only in the development version, I'll move it to the main version next week. I'll reopen the issue until then, and think about a small interface and frame to add to the example.

**Comment by spetitjean** [comment]
It should look like this soon (here with predicate semantics):
![interface](https://user-images.githubusercontent.com/13102091/48266822-dfda7800-e430-11e8-97ee-59d0397cc1ee.png)

**Comment by spetitjean** [comment]
Available in the current version. The starting example now includes a small frame and a small interface.
