### ISSUE TITLE
Frame hierarchy is not taken into account in XMG WebGUI

### ISSUE THREAD

**Issue by eseyffarth** [xmg-hhu/xmg-webgui#17]
Scenario: Parsing a sentence in the XMG WebGUI parser that is supposed to be blocked by the frame type hierarchy, e.g. "the fence jumped".
Behavior: The viewer shows a frame for this sentence where the subject has two types that are specified in the frame type hierarchy to be incompatible.
Expected behavior: The parser should not generate a tree and frame for this sentence because the types "physical_object" and "animate" are specified in the frame type hierarchy to be incompatible.

The same grammar files and type hierarchy lead to the correct behavior in the XMG Ubuntu VM - the sentence is blocked, with the output:
> Incompatible types: [physical_object-fence] and [animate-entity]
Frame unification failed, tree discarded

Included:
- Screenshot from XMG WebGUI output for "the fence jumped"
- Screenshot from Tulipa output in XMG Ubuntu VM for "the fence jumped"
- .mg files and .xml files with a minimal working example metagrammar illustrating the issue (renamed to .mg.txt and .xml.txt to circumvent GitHub's restriction for file uploads...)

![the_fence_jumped_webgui](https://user-images.githubusercontent.com/8790676/173090656-8e718fb4-cd56-4c7e-8599-49f00517ee23.PNG)
![the_fence_jumped_xmgvm](https://user-images.githubusercontent.com/8790676/173090660-c36d71e1-c0ec-4915-aeb2-f2aca6124978.PNG)
[frame_dimension.mg.txt](https://github.com/xmg-hhu/xmg-webgui/files/8879842/frame_dimension.mg.txt)
[frame_dimension.xml.txt](https://github.com/xmg-hhu/xmg-webgui/files/8879843/frame_dimension.xml.txt)
[lemma.mg.txt](https://github.com/xmg-hhu/xmg-webgui/files/8879844/lemma.mg.txt)
[lemma.xml.txt](https://github.com/xmg-hhu/xmg-webgui/files/8879845/lemma.xml.txt)
[morph.mg.txt](https://github.com/xmg-hhu/xmg-webgui/files/8879846/morph.mg.txt)
[morph.xml.txt](https://github.com/xmg-hhu/xmg-webgui/files/8879847/morph.xml.txt)
[syn_dimension.mg.txt](https://github.com/xmg-hhu/xmg-webgui/files/8879848/syn_dimension.mg.txt)
[syn_dimension.xml.txt](https://github.com/xmg-hhu/xmg-webgui/files/8879849/syn_dimension.xml.txt)

**Comment by spetitjean** [comment]
Thanks a lot for the report!
So, this is more a TuLiPA bug, right? Or do the local and online versions of XMG produce different outputs?
I will have a look as soon as possible, maybe 3 more things could help the diagnostic until then:

- in the online TuLiPA console output, can you see if the type hierarchy is correctly loaded? 
- is it correct that in both cases, the CYKTAG parser is used?
- are you able to check which version of TuLiPA (which commit, ideally) is provided in the VM? I forgot if this is only a jar file or the whole git repository.

**Comment by spetitjean** [comment]
So, the bug is the following: the type hierarchy is not used because the file size is above the limit fixed by the server. 
For instance, adding the constraint "physical_object -> entity" reduces the size of the hierarchy from 4Mb to 1, and the parsing produces the expected output.
We should think about increasing the size limit on the server, and definitely display an error message when uploads fail (it is actually the case when the grammar file is too large).
In the meantime, when large hierarchies are needed, I could only suggest to use the latest desktop version of TuLiPA (https://github.com/spetitjean/TuLiPA-frames/raw/master/TuLiPA-frames.jar).

**Comment by eseyffarth** [comment]
This is perfectly helpful, adding constraints to make the type hierarchy smaller fixed the issue for me! Thank you!

**Comment by spetitjean** [comment]
Great, I will leave the issue open until we fix the missing error message then :)

**Comment by spetitjean** [comment]
The error messages for upload fails are fixed.
