### ISSUE TITLE
No tree display when no frame dimension

### ISSUE THREAD

**Issue by spetitjean** [xmg-hhu/xmg-webgui#6]
When no frame description is given, the viewer does not display the entry.
To be more precise, an xml with:
```
...
</tree>
<frame/>
<interface>
...
```
displays an empty frame while one with the following crashes:
```
...
</tree>
<interface>
...
```
Fixing this should allow to see all the grammars created with XMG1 (the syntactic part at least).

**Comment by timmli** [comment]
I've updated `xmgview.js`. Please try if it works now.

**Comment by spetitjean** [comment]
Beautiful!
