### ISSUE TITLE
XML with atomic disjunctions in feature structures 

### ISSUE THREAD

**Issue by spetitjean** [xmg-hhu/xmg-webgui#7]
I realised that the viewer crashes when seeing atomic disjunctions as values of features, as in the following feat for example:
```
               <f name="mode">
                  <vAlt coref="@AD4">
                    <sym value="ind"/>
                    <sym value="subj"/>
                  </vAlt>
                </f>
```

The error is apparently in xmgview.js, line 423:
  
`				value.setAttribute("x", maxlengthFeatures + 10); //padding `

**Comment by timmli** [comment]
I don't experience a problem when I add a disjunction like this:

    	node ?VP1 [cat = {vp|np},bot=[path=?X3] ]{

The xml file that is generated with the webgui doesn't use `vAlt` but stores two separate models. The problem you describe seems to emerge when uploading a compiled grammar with `vAlt`. Indeed, `xmgview.js` does not expect `vAlt`, so `value` is not instantiated.

Can you please attach one complete example?

**Comment by spetitjean** [comment]
Oh, yes, that is a different thing. An atomic disjunction would be something like this:

`	node ?VP1 [cat = @{vp,np},bot=[path=?X3] ]{`

**Comment by spetitjean** [comment]
Here is a complete - and probably linguistically meaningless -  example just in case (to be compiled with synsem):
[TagExample_adisj.zip](https://github.com/xmg-hhu/xmg-webgui/files/1597014/TagExample_adisj.zip)

**Comment by timmli** [comment]
Bedankt! So what is the difference between "atomic disjunction" and the sort of disjunction that I was using?

**Comment by spetitjean** [comment]
Atomic disjunctions are the way to give an underspecified value without creating creating several models (like in your example). They usually only appear in the metagrammar and not in the grammar (as nodes get unified, the underspecification rarely remains), but they can still be found. TuLiPA for instance knows how to play with them.
