### ISSUE TITLE
Frames stop being displayed

### ISSUE THREAD

**Issue by spetitjean** [xmg-hhu/xmg-webgui#8]
In a grammar with trees and frames, if some of the entries contain no frame, their selection cause the frames of the other entries to be ignored. 
As long as entries with tree+frame are selected, the display works fine, it is only when a tree-no_frame entry is selected that frames stopped being displayed.

**Comment by timmli** [comment]
Can you post an example? Thanks!

**Comment by spetitjean** [comment]
Sure, sorry, this should be more understandable:
[french_v3.zip](https://github.com/xmg-hhu/xmg-webgui/files/1597001/french_v3.zip)

The two first trees (adj and det) have no frame. When selecting, any other tree, their frame is displayed, but as long as one of these is selected, the frames for the other trees stop being displayed. 

The types of frames also disappear after some time, but I cannot really see what triggers it yet.

**Comment by spetitjean** [comment]
I fixed it. An error is displayed instead (I cannot fix it, because I cannot edit the file script.js where it happens).
